# Generated by Django 5.0.2 on 2024-03-05 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatagory',
            fields=[
                ('pro_cat_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('pro_cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.PositiveIntegerField()),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_price', models.PositiveIntegerField()),
                ('pro_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcatagory')),
            ],
        ),
    ]
